### ISSUE TITLE
JSON-style array inside quotes parsed as arrays.

### ISSUE THREAD

**Issue by Verox-** [zaach/jsonlint#65]
Strings which look like JSON arrays are parsed as arrays (and will throw an error.)

For example:
`"pos": "[106.675,525.792,47.7364]"` is entirely valid JSON but will error out with `Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['` when linted.

**Comment by rodionovd** [comment]
@Verox- could you provide a full JSON?   

The given sample works for me:
```bash
$ cat foo.json
["pos": "[106.675,525.792,47.7364]"]
$ jsonlint -q foo.json
# jsonlint outputs no errors
```

**Comment by Verox-** [comment]
I don't have the full JSON that was causing the issue anymore, but it does seem to be working with similar JSON now. 

I'm certain this was an issue with, or at least related to, arrays in quotes as removing the quotes fixed the issue and it parsed correctly; this was reproducible over a few days and many different JSON objects.

I suppose you can close this as unreproducible for now, if I manage to reproduce it I'll create another report with more detail and a full example.

**Comment by rodionovd** [comment]
I'm not an owner of this repository and can't close other's issues… So it's up to you :smile:

**Comment by Verox-** [comment]
Ah, well, in that case...
